### ISSUE TITLE
Is concerto pip installable?

### ISSUE THREAD

**Issue by djinnome** [pnnl-predictive-phenomics/concerto#1]

**Comment by JamesPino** [comment]
Working on this. Refactored repo. Need permissions to create releases and edit repo. Being able to create and delete at the repo admin level, even temporary, will simplify this process. I need to create tests 'tags' for release triggers.  Is that possible @djinnome.

**Comment by djinnome** [comment]
I just upgraded you to admin on the concerto repo.  Sorry for the hassle.

**Comment by JamesPino** [comment]
PR submitted. It is quite large, but its a big refactoring, removals of stuff not related to concerto (older models and data), and structuring for the package itself. The second PR has the cookie cutter template in it. We are going to put it under heavier tests today to make sure it works as expected, but the prepare for pypi PR should be good.
