### ISSUE TITLE
Generate a mediadb file for carveme that takes the Biolog carbon plates and the carbonless media as input.

### ISSUE THREAD

**Issue by djinnome** [pnnl-predictive-phenomics/concerto#20]
The media database for CarveME is described here:

https://carveme.readthedocs.io/en/latest/advanced.html#media-database

medium | description | compound | name
-- | -- | -- | --
LB | Lysogeny broth | adn | Adenosine
LB | Lysogeny broth | ala__L | L-Alanine
LB | Lysogeny broth | amp | AMP
LB | Lysogeny broth | arg__L | L-Arginine
LB | Lysogeny broth | aso3 | Arsenite
LB | Lysogeny broth | asp__L | L-Aspartate

The Biolog carbonless growth media for Memote is described here:
https://github.com/pnnl-predictive-phenomics/csc009-gem/blob/main/csc009/data/media/csc009C-less_media.csv

The carbon sources that the organism grows on is defined here:
https://github.com/pnnl-predictive-phenomics/csc009-gem/blob/main/csc009/data/growth/biolog_carbon_curtobacterium1.csv

exchange | growth | uptake
-- | -- | --
EX_cs_c_e | False | 10
EX_dextrin_e | True | 10
EX_glycogen_e | False | 10
EX_mannan_e | False | 10
...

Here are the Bigg IDs for the carbonless biolog media, 

|Bigg id| Name|
|-------|-----------|
|cl|Chloride|
|na1|Sodium|
|nh4|Ammonium|
|pi|Phosphate|
|k|Potassium|
|so4|Sulfate|
|fe3|Iron|

but maybe what is in `csc009C-less_media.csv` is easier to gapfill on.

We want to take the memote carbon sources that the organism actually grows on, add the carbonless media, and create a mediadb entry.

**Comment by mcnaughtonadm** [comment]
Example of a CarveMe biolog media can be found [here](https://github.com/pnnl-predictive-phenomics/csc009-gem/blob/3394b1732ccb1ff190fa8b9c35dab48b71ef0b1f/csc009/data/media/CarveMeMinimalMediaFile.csv)

**Comment by augeorge** [comment]
@tiekneeshrimp 

the function we need to write should do the following:

- [ ] input a carbonless minimal media csv file (i.e., https://github.com/pnnl-predictive-phenomics/csc009-gem/blob/main/csc009/data/media/csc009C-less_media.csv),

- [ ] input a biolog growth csv file (i.e., https://github.com/pnnl-predictive-phenomics/csc009-gem/blob/main/csc009/data/growth/biolog_carbon_curtobacterium1.csv)

- [ ] get the list of carbon sources that grow from the biolog growth file. we did this yesterday.

- [ ] create a pandas dataframe of the carbonless minimal media and make sure it has the correct formatting for carvemen (medium | description | compound | name). 

- [ ] loop through each carbon source in the list of carbon sources, copy all the carbonless minimal media and append them to the dataframe (renaming them based on the carbon source medium), also add a new row for the carbon source itself. 

- [ ] the end result should be a dataframe that has a "section" for each carbon source + minimal growth sources, and the original minimal growth sources. each section will mostly be the same except for the name column and carbon source. see the example https://github.com/pnnl-predictive-phenomics/csc009-gem/blob/3394b1732ccb1ff190fa8b9c35dab48b71ef0b1f/csc009/data/media/CarveMeMinimalMediaFile.csv
